### ISSUE TITLE
Model missing from HF

### ISSUE THREAD

**Issue by sammcj** [kolinko/effort#3]
kolinko/mistral-buckets appears to have gone from Huggingface?

```
huggingface-cli download 'kolinko/mistral-buckets' --exclude "*Q8*" --local-dir ./models/mistral             (main)
Traceback (most recent call last):
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/samm/.venv/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/kolinko/mistral-buckets/revision/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/samm/.venv/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/commands/huggingface_cli.py", line 49, in main
    service.run()
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/commands/download.py", line 161, in run
    print(self._download())  # Print path to downloaded files
          ^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/commands/download.py", line 202, in _download
    return snapshot_download(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 255, in snapshot_download
    raise api_call_error
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/_snapshot_download.py", line 186, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/hf_api.py", line 2418, in repo_info
    return method(
           ^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/hf_api.py", line 2228, in model_info
    hf_raise_for_status(r)
  File "/Users/samm/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-662041c5-675d69672e2a2336497abb37;cc6e7f1c-44c1-48ed-a64f-9d0f3c8e2d41)

Repository Not Found for url: https://huggingface.co/api/models/kolinko/mistral-buckets/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
```

**Comment by sammcj** [comment]
Looking at HF, I can't see any models under your username: https://huggingface.co/kolinko

Did you perhaps forget to make them public?

**Comment by kolinko** [comment]
Ah! Yes, forgot to make them public.

Thank you! Fixed.

**Comment by sammcj** [comment]
that's more like it! Thanks :)

```
 huggingface-cli download 'kolinko/mistral-buckets' --exclude "*Q8*" --local-dir ./models/mistral                 (main)
downloading https://huggingface.co/kolinko/mistral-buckets/resolve/3680b2b00733ded603863d868c4ae524ab176838/.gitattributes to /Users/samm/.cache/huggingface/hub/tmplc2hycwp
.gitattributes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 1.52k/1.52k [00:00<00:00, 2.59MB/s]
downloading https://huggingface.co/kolinko/mistral-buckets/resolve/3680b2b00733ded603863d868c4ae524ab176838/README.md to /Users/samm/.cache/huggingface/hub/tmpnme8kndz
README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 58.0/58.0 [00:00<00:00, 501kB/s]
downloading https://huggingface.co/kolinko/mistral-buckets/resolve/3680b2b00733ded603863d868c4ae524ab176838/buckets-FP16-00001-of-00032.safetensors to /Users/samm/.cache/huggingface/hub/tmppfcr0cr7
buckets-FP16-00001-of-00032.safetensors: 100%|███████████████████████████████████████████████████████████████████▉| 1.05G/1.05G [00:11<00:00, 90.6MB/s]
```
